### ISSUE TITLE
Issue with PyQt for python 2.7

### ISSUE THREAD

**Issue by BasvdHerik** [SystemsBioinformatics/cbmpy-metadraft#1]
Hi,

While trying to run metadraft.py after okay from systemtest.py i got the message: '2' after showing the icon, this was while running on python 2.7 using PyQt4.
I did update to PyQt5, however I then got an error message showing that no module named sip was available, this module dropped support for python versions below v3.5 as stated on their website.

Kind regards,
Bas

Edit: i also get the 2 using python 3.5

**Comment by bgoli** [comment]
HI, thanks for your message. 

This is rather strange and some more information might help, are you trying to install the dependencies with pip or Anaconda, which OS are you using? Could you take a look at the syslog files (they are in the metadraft/log directory) and  see if there is a more detailed error message there. 

Regards, Brett

**Comment by BasvdHerik** [comment]
I did install the dependencies using anaconda on Windows 10. 

Using python 3.5 and Qt5 it gives this error in the syslog:
ERROR:STDERR:[WinError 3] The system cannot find the path specified: 'C:\\Users\\640208\\Desktop\\metadraft\\cbmpy-metadraft-master\\modeldb\\2018-1\\lib_model'
The folder lib_model is not present in 2018-1, instead lib_metaproteome is present. 

Hope this helps.

Bas

**Comment by BasvdHerik** [comment]
Solved. Models from the repository were not present in lib_model. After cloning the repository again they were not present again, by copying them manually into lib_model MetaDraft was started without problems on python 3.5.

**Comment by bgoli** [comment]
Hi, yes that was the problem, I have added a fix that will not cause a crash. The template models are actually available as a git submodule. Out of interest, did you try this step, which I now notice was really badly formatted in the readme?

`cd cbmpy-metadraft` 

`git submodule update --init --remote -- modeldb/2018-1/`

**Comment by BasvdHerik** [comment]
I do not use that step, I installed it without git. Would have been easier using git and following that step.

**Comment by bgoli** [comment]
Thank you for your input that is very helpful. I will improve the release information so that it makes it easier to add the template libraries when downloading a release.
