### ISSUE TITLE
Instalation OK, system test OK, run cannot find sip although it is installed

### ISSUE THREAD

**Issue by NatashaJorge** [SystemsBioinformatics/cbmpy-metadraft#15]
Hello,

I'm trying to install and run MetaDraft, I've run the following commands:

$  conda env create -f environment.yml (for installation)

$ conda activate metadraft3

(metadraft3) $  python systemtest.py

Which gives me:

System check results:
=====================
Java test passed: True
Perl test passed: True
Perl XML test passed: True
BLAST test passed: True
Python dependency test passed: True

Congratulations you are ready to run MetaDraft! (python metadraft.py)

However, when I run:

(metadraft3) $ sh ./run.sh

I get the following error:

Traceback (most recent call last):
  File "metadraft.py", line 62, in <module>
    import libpython.qtmetadraft
  File "/scr/k61san/natasha/matomic/metadraft/cbmpy-metadraft-0.9.5/libpython/qtmetadraft.py", line 40, in <module>
    import sip
ModuleNotFoundError: No module named 'sip'

Even though sip is installed

(metadraft3) $ pip install sip

Requirement already satisfied: sip in /homes/brauerei/natasha/miniconda3/envs/metadraft3/lib/python3.8/site-packages (6.5.1)
Requirement already satisfied: setuptools in /homes/brauerei/natasha/miniconda3/envs/metadraft3/lib/python3.8/site-packages (from sip) (60.9.3)
Requirement already satisfied: toml in /homes/brauerei/natasha/miniconda3/envs/metadraft3/lib/python3.8/site-packages (from sip) (0.10.2)
Requirement already satisfied: packaging in /homes/brauerei/natasha/miniconda3/envs/metadraft3/lib/python3.8/site-packages (from sip) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /homes/brauerei/natasha/miniconda3/envs/metadraft3/lib/python3.8/site-packages (from packaging->sip) (3.0.7)

Please, can you help me? What can I do to run metadraft ?

Thanks in advance

**Comment by bgoli** [comment]
Thanks for the detailed report, could you try build the conda environment with the attached environment.yml file (zipped) and see if that works
[environment.zip](https://github.com/SystemsBioinformatics/cbmpy-metadraft/files/8196563/environment.zip)
?

**Comment by NatashaJorge** [comment]
Hi!

Thanks for the reply, but I'm getting the same error message:

(metadraft3) [natasha@k61 cbmpy-metadraft-0.9.5]$ python systemtest.py
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

This is perl, v5.10.1 (*) built for x86_64-linux

Copyright 1987-2009, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

[formatdb] ERROR: No database name was specified
GLPK not available

*****
Using CPLEX
*****



***********************************************************************
* Welcome to CBMPy (0.8.2) - PySCeS Constraint Based Modelling        *
*                http://cbmpy.sourceforge.net                         *
* Copyright(C) Brett G. Olivier 2014 - 2020                           *
* Systems Biology Lab, Vrije Universiteit Amsterdam                   *
* Amsterdam, The Netherlands                                          *
* CBMPy is developed as part of the BeBasic MetaToolKit Project       *
* Distributed under the GNU GPL v 3.0 licence, see                    *
* LICENCE (supplied with this release) for details                    *
***********************************************************************



System check results:
=====================
Java test passed: True
Perl test passed: True
Perl XML test passed: True
BLAST test passed: True
Python dependency test passed: True

Congratulations you are ready to run MetaDraft! (python metadraft.py)

(metadraft3) [natasha@k61 cbmpy-metadraft-0.9.5]$ sh ./run.sh
Traceback (most recent call last):
  File "metadraft.py", line 62, in <module>
    import libpython.qtmetadraft
  File "/scr/k61san/natasha/matomic/software/metadraft/cbmpy-metadraft-0.9.5/libpython/qtmetadraft.py", line 40, in <module>
    import sip
ModuleNotFoundError: No module named 'sip'
(metadraft3) [natasha@k61 cbmpy-metadraft-0.9.5]$

**Comment by NatashaJorge** [comment]
Oh, and sip is really there, just not being recognized

$ ls /homes/brauerei/natasha/miniconda3/envs/metadraft3/bin/ | grep sip
sip
sip-build
sip-distinfo
sip-install
sip-module
sip-sdist
sip-wheel

**Comment by Jadelrea** [comment]
I have the same problem

**Comment by NatashaJorge** [comment]
Hey!

just to inform in case  anyone has this problem also. I was able to fix it by adding this line:

pip install PyQt5-sip

in the beginning of the metadraft.py file.

best,
Natasha

**Comment by pavlohrab** [comment]
Same error here. Helped substituting `import sip` with `from PyQt5 import sip` in `libpython/qtmetadraft.py`, as suggested [here](https://stackoverflow.com/questions/55087069/no-module-named-pyqt5-sip)

**Comment by bgoli** [comment]
Hi, thanks for adding the great advice. It may be of interest that in the dev branch I am currently testing the next version of metadraft which removes the sip dependency altogether.

**Comment by bgoli** [comment]
this is now fixed in both dev and main branches
